owner: roado
repo: uptime
# Uncomment for a self-hosted runner
# runner: "[self-hosted, linux, ARM64]"
# WARN: Don't change the commit messages they seem to break the uptime status

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: Landing Page
    url: https://www.roado.co.in
  - name: Fleet
    url: https://fleet.roado.tech/
  - name: Industry
    url: https://industry.roado.tech/
  - name: Beta
    url: https://beta.roado.co.in/
  - name: Roadoapi
    url: https://api.roado.co.in/serverCheck
  - name: mdash
    url: https://api.roado.co.in/fleet/api/health-check
assignees:
  - charitya16

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/roado/uptime/master/assets/RoaDoLogoHorizontal.svg
  favicon: https://raw.githubusercontent.com/roado/uptime/master/assets/logo_64x64.png
  name: Uptime
  introTitle: "This is an uptime monitor RoaDo apps."
  introMessage: This app monitors all the applications from RoaDo. It is powered by the open source tools [Upptime](https://github.com/upptime/upptime) and github actions.
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
